### ISSUE TITLE
Display long title for divisions in backend relations instead of title

### ISSUE THREAD

**Issue by Astraeus-** [Fabian-Sommer/HeroesLounge#15]
**Division selector drop-down**
![backend create match division selector](https://user-images.githubusercontent.com/6303961/43677020-a02b4b5c-97fb-11e8-92eb-7a551c9853eb.PNG)

Associating a match with a division or playoff group, requires you to select the correct one out of multiple similarly named divisions or groups. Specifying a season would resolve this problem for regular season games.

However for Championship and Cup matches this wouldn't solve much. E.g: You'd still need to guess which "Group A" belongs to the Championship or the Cup.
Potential future tournaments will also not have a season that they're associated with and probably run into similar problems as mentioned above with the groups from the Cup and the Championship.

**Comment by Fabian-Sommer** [comment]
May or may not be possible with the framework

**Comment by rogusdev** [comment]
For starters on creating a match, could you change `nameFrom: title` in plugins\rikki\heroeslounge\models\match\fields_on_create.yaml to something like the new `nameFrom: overview_display_title` and it would do what you want?  As in, will that be populated appropriately?  Or is there some way to reference a calculated field on the model rather than a db field?  And the calculated field be some method on the model plugins\rikki\heroeslounge\models\Match.php somehow?

**Comment by Astraeus-** [comment]
Changing to `nameFrom: overview_display_title` would not work as not every division has this defined. You'd get a long list of blanks with two named `Standings` for the division S divisions. The [OctoberCMS Documentation](https://octobercms.com/docs/backend/forms) has the various things that would be possible. I think the best way to go about this is to probably create a custom dropdown instead of relying on the relation.
