### ISSUE TITLE
Default stats to NA season for NA players

### ISSUE THREAD

**Issue by stephwang** [Fabian-Sommer/HeroesLounge#50]
When viewing user profiles for for an NA user, the season dropdown still defaults to EU Season 8 (e.g. "Displaying stats of [EU]Season 8"). We should default this to "[NA]Season 1".

**Comment by Astraeus-** [comment]
With the addition of division s seasons, defined by their `type` on the season, we should consider filtering according to a matching team `type` as well.

@stephwang Are you still interested in working on this?

**Comment by rogusdev** [comment]
The page in question for a player/user/sloth is:
http://localhost:8080/hl/user/view/55

And the place to select a default regional season is:
plugins\rikki\loungestatistics\components\slothstatistics\default.htm

However, which season should be the default in a given region?  What is the algo/criteria for which one to pick?

Also, the same regional season dropdown appears to exist for teams:
plugins\rikki\loungestatistics\components\teamstatistics\default.htm

which comes from clicking the Statistics tab for a team:
http://localhost:8080/hl/team/view/CPK

Same question on how to calculate the preferred default for a team.

**Comment by rogusdev** [comment]
Worth noting that region in the db:
```
SELECT * FROM rikki_heroeslounge_regions;
+----+-------+
| id | title |
+----+-------+
|  1 | EU    |
|  2 | NA    |
+----+-------+
2 rows in set (0.01 sec)
```

And the division type that @Astraeus- mentioned:
```
SELECT * FROM rikki_heroeslounge_seasons ORDER BY id DESC LIMIT 4 \G;
*************************** 1. row ***************************
           id: 9
        title: [EU] Division S Season 1
 round_length: 3
         slug: eu-division-s-season-1
current_round: 0
    is_active: 1
   created_at: 2019-03-06 02:02:17
   updated_at: 2019-03-06 02:02:17
   deleted_at: NULL
     reg_open: 0
    mm_active: 0
    region_id: 1
         type: 2
        other: NULL
*************************** 2. row ***************************
           id: 8
        title: [EU]Season 9
 round_length: 10
         slug: euseason-9
current_round: 0
    is_active: 1
   created_at: 2019-02-03 14:19:31
   updated_at: 2019-02-03 18:48:37
   deleted_at: NULL
     reg_open: 1
    mm_active: 0
    region_id: 1
         type: 1
        other: NULL
```
^ DivS is type 2, regular seasons are type 1, it seems

**Comment by Fabian-Sommer** [comment]
You are right that for any type, AmateurSeries is 1 and DivS is 2. The default season should be:
- The oldest season
- which is active
- that the team participated in (this should cover having the correct type and region)

If participation is too expensive to find out, it is ok to just check for matching type and region.

**Comment by rogusdev** [comment]
I'll see if I can do this one

**Comment by rogusdev** [comment]
> The oldest season

Do you actually mean the most recent one?  Or if there are 2 active seasons the team/sloth participated in, you want the least recent one?

**Comment by rogusdev** [comment]
"participation"in a season means that there is a game for that team in `rikki_heroeslounge_season_team`?  And for a sloth, it would be that the sloth is in team_apps for a team that is in ^?  The sloth one sounds... complicated.  Is there any reason that `$allseasons` for those statistics pages are not already limited to the region of the sloth/team?

**Comment by rogusdev** [comment]
I see https://github.com/Fabian-Sommer/HeroesLounge/blob/db750d7e6e9b0ac941fb93cdf020791a6aeccf3c/plugins/rikki/heroeslounge/classes/mailchimp/MailChimpAPI.php#L19 for `Season::where('id', 3)...->divisions` (side note: very odd to see that fixed to a particular season id...) and I also see https://github.com/Fabian-Sommer/HeroesLounge/blob/db750d7e6e9b0ac941fb93cdf020791a6aeccf3c/plugins/rikki/loungeviews/components/DivisionOverview.php#L23 for `Season::with('divisions')...` -- should I just do `::with('teams')` and then search through $season->teams or is there a way to do join query in this ORM?

**Comment by Fabian-Sommer** [comment]
Its the oldest season because often, there are two overlapping (active) seasons: One (older) that is still in progress and a newer one where signups are open but no games have yet been played.

> "participation"in a season means that there is a game for that team in `rikki_heroeslounge_season_team`? And for a sloth, it would be that the sloth is in team_apps for a team that is in ^? The sloth one sounds... complicated. Is there any reason that `$allseasons` for those statistics pages are not already limited to the region of the sloth/team?

Participation should be defined as there is a game/match which is part of the season, this can be either through match->division->season or match->tournament->season or match->division->tournament->season. Ignore team_apps - a sloth having applied to a team does not mean he played for them, instead you can use sloth->gameparticipations.

The stats pages are older than regions, so $allseasons has not been optimized to account for that. Feel free to do it if you want, low priority.




> I see:
> [HeroesLounge/plugins/rikki/heroeslounge/classes/mailchimp/MailChimpAPI.php](https://github.com/Fabian-Sommer/HeroesLounge/blob/db750d7e6e9b0ac941fb93cdf020791a6aeccf3c/plugins/rikki/heroeslounge/classes/mailchimp/MailChimpAPI.php#L19)
> 
> Line 19 in [db750d7](/Fabian-Sommer/HeroesLounge/commit/db750d7e6e9b0ac941fb93cdf020791a6aeccf3c)
> 
>  		$activeUsers = Season::where('id', 3)->firstOrFail()->divisions 
> 
> for `Season::where('id', 3)...->divisions` (side note: very odd to see that fixed to a particular season id...)
> and I also see:
> [HeroesLounge/plugins/rikki/loungeviews/components/DivisionOverview.php](https://github.com/Fabian-Sommer/HeroesLounge/blob/db750d7e6e9b0ac941fb93cdf020791a6aeccf3c/plugins/rikki/loungeviews/components/DivisionOverview.php#L23)
> 
> Line 23 in [db750d7](/Fabian-Sommer/HeroesLounge/commit/db750d7e6e9b0ac941fb93cdf020791a6aeccf3c)
> 
>          $s = Season::with('divisions')->where('slug',$this->param('slug'))->first(); 
> 
> for `Season::with('divisions')...`
> Should I just do `::with('teams')` and then search through $season->teams or is there a way to do join query in this ORM? I see for joins:
> [HeroesLounge/plugins/rikki/heroeslounge/models/Division.php](https://github.com/Fabian-Sommer/HeroesLounge/blob/db750d7e6e9b0ac941fb93cdf020791a6aeccf3c/plugins/rikki/heroeslounge/models/Division.php#L106)
> 
> Line 106 in [db750d7](/Fabian-Sommer/HeroesLounge/commit/db750d7e6e9b0ac941fb93cdf020791a6aeccf3c)
> 
>          $q->join('rikki_heroeslounge_seasons as season','rikki_heroeslounge_divisions.season_id','=','season.id')->where('season.is_active',true);

Please ignore the MailChimp, the code you quoted was from initial data migration, hence the hardcoded value.

As to querying, there is a way to piece together SQL queries (which I would not do unless there is no other way, it still happens in our codebase here and there) where you can do joins. A better way to do it is just $season->teams - this always works and is being translated into a join query in the background without explicitly using joins. Getting $season by Season::with(...) just speeds it up by joining season and teams in the initial query instead of first fetching the season and doing a separate join later. Of course, speedup is good, so using with(...) is encouraged when you know that you will use the relation.

Back to the specific problem at hand: Please do not use Season->teams, this is only used during signups and may not contain all competing teams. Define participation through played games.
